# Generated by Django 5.2.3 on 2025-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_specialoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('restaurant', 'Restaurant')], max_length=20),
        ),
    ]
